# Generated by Django 4.2.7 on 2023-12-10 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msgfeedApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='msgfeedApp.person'),
        ),
    ]
