# Generated by Django 4.2.7 on 2023-12-10 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgfeedApp', '0002_message_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
