# Generated by Django 4.2.7 on 2023-12-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgfeedApp', '0003_alter_message_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='tags',
            field=models.ManyToManyField(to='msgfeedApp.tag'),
        ),
    ]
