# Generated by Django 4.2.7 on 2023-12-10 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgfeedApp', '0004_tag_message_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
