# Generated by Django 4.2.7 on 2023-12-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgfeedApp', '0006_person_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=500, null=True)),
                ('username', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='message',
            name='like',
        ),
        migrations.AddField(
            model_name='comment',
            name='message_id',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='no_of_likes',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='person',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
