# Generated by Django 4.2.7 on 2023-12-13 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msgfeedApp', '0007_like_remove_comment_like_remove_message_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='message_id',
            new_name='Like_id',
        ),
    ]
