# Generated by Django 4.2.7 on 2023-12-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msgfeedApp', '0009_rename_message_id_comment_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='no_of_comments',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
